#!/usr/bin/env bash
# Bootstraps a brand new system
set -eu

brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# export SYSTEM_VERSION_COMPAT=1
# sudo rm -rf /Library/Developer/CommandLineTools  # force CLT to be reinstalled
# Install manually from https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12/Command_Line_Tools_for_Xcode_12.dmg
# softwareupdate --install -a  # install XCode
# xcode-select --install || true
# sudo xcodebuild -license accept

(
  mkdir -p ~/git/github.com/mrdefenestrator/
  cd ~/git/github.com/mrdefenestrator/
  git clone https://github.com/mrdefenestrator/environment.git || true
  cd environment/

  ./install-packages

  ./link

  # shellcheck disable=SC1090
  source "${HOME}/.profile"
)
