#!/usr/bin/env bash
# Bootstraps a brand new system
set -eu -o pipefail

brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

export SYSTEM_VERSION_COMPAT=1
# sudo rm -rf /Library/Developer/CommandLineTools  # force CLT to be reinstalled
# Install manually from https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12/Command_Line_Tools_for_Xcode_12.dmg
# softwareupdate --install -a  # install XCode
# xcode-select --install || true
sudo xcodebuild -license accept

base_dir="${HOME}/git/github.com/mrdefenestrator/"
mkdir -p "${base_dir}"
(
  cd "${base_dir}"
  git clone git://github.com/mrdefenestrator/environment.git || true
  cd environment/
  # ./install-packages

  grep '/usr/local/bin/bash' /etc/shells || sudo sh -c "echo /usr/local/bin/bash >> /etc/shells"
  chsh -s /usr/local/bin/bash

  ./link

  # shellcheck disable=SC1090
  source "${HOME}/.profile"
)
