#!/usr/bin/env bash
# Bootstraps a brand new system
set -eux -o pipefail

brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# sudo rm -rf /Library/Developer/CommandLineTools
# xcode-select --install || true
# sudo xcodebuild -license accept

base_dir="~/git/github.com/mrdefenestrator/"
mkdir -p "${base_dir}"
echo "$base_dir"
pwd
(
  cd "${base_dir}"
  pwd
  git clone git://github.com/mrdefenestrator/environment.git || true
  cd environment/
  ./install-packages

  grep '/usr/local/bin/bash' /etc/shells || sudo sh -c "echo /usr/local/bin/bash >> /etc/shells"
  chsh -s /usr/local/bin/bash

  ./link

  # shellcheck disable=SC1090
  source "${HOME}/.profile"
)
