#!/usr/bin/env bash
# Installs all persisted mas packages
set -eu

brew install $(cat brew-requirements.txt)
brew cask install $(cat brew-cask-requirements.txt)
mas install $(cat mas-requirements.txt | sed -E "s/([0-9]+).*/\1/g")
#cat mas-requirements.txt | sed -E "s/([0-9]+).*/\1/g" | xargs -I {} sh -c 'mas install {}'
cat mas-requirements.txt | xargs -I {} sh -c 'code --install-extension {}'

