#!/usr/bin/env bash
# Create symlinks throughout system to linkables
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function _backup_and_link {
  local link_in_dir="${1}"
  local linkables_dir="${2}"
  local file_to_link="${3}"

  if [[ -L "${link_in_dir}/${file_to_link}" ]]; then
    ln -sf "${linkables_dir}/${file_to_link}" "${link_in_dir}/${file_to_link}"
    >&2 echo "${file_to_link} already linked, updated anyway"
  else
    if [[ -f "${link_in_dir}/${file_to_link}" ]]; then
      cp -r "${link_in_dir}/${file_to_link}" "${link_in_dir}/${file_to_link}.bak"
    fi
    ln -sf "${linkables_dir}/${file_to_link}" "${link_in_dir}/${file_to_link}"
    >&2 echo "${file_to_link} linked"
  fi
}

function backup_and_link {
  local link_in_dir="${1}"
  local linkables_dir="${2}"
  local file_to_link="${3}"

  local owner
  # shellcheck disable=SC2012
  owner="$(ls -ld "${link_in_dir}/${file_to_link}" | awk '{print $3}')"

  if [[ "${owner}" == "root" ]]; then
    >&2 echo "elevating to root"
    sudo bash -c "$(declare -f _backup_and_link); _backup_and_link \"${link_in_dir}\" \"${linkables_dir}\" \"${file_to_link}\""
  else
    _backup_and_link "${link_in_dir}" "${linkables_dir}" "${file_to_link}"
  fi
}

main() {
  local base="${DIR}/linkables/HOME"
  # shellcheck disable=SC2044
  shopt -s globstar nullglob
  for linkable in "${base}/"{.*,*,**/*,**/.*}; do
    if [[ -f "${linkable}" ]]; then
      backup_and_link "${HOME}" "${base}" "${linkable#${base}/}"
    fi
  done

  base="${DIR}/linkables/ROOT"
  # shellcheck disable=SC2044
  shopt -s globstar nullglob
  for linkable in "${base}/"{.*,*,**/*,**/.*}; do
    if [[ -f "${linkable}" ]]; then
      backup_and_link "/" "${base}" "${linkable#${base}/}"
    fi
  done
}

main "$@"
