#!/usr/bin/env bash
# Create symlinks
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function backup_and_link {
  if [[ -L "${HOME}/$1" ]]; then
    ln -sf "${DIR}/linkables/$1" "${HOME}/$1"
    echo "$1 already linked, updated anyway"
  else
    if [[ -f "${HOME}/$1" ]]; then
      cp -r "${HOME}/$1" "${HOME}/$1.bak"
    fi
    ln -sf "${DIR}/linkables/$1" "${HOME}/$1"
    echo "linked $1"
  fi
}

backup_and_link .profile
backup_and_link .git-status
backup_and_link .nanorc
backup_and_link .gitconfig
backup_and_link .inputrc
backup_and_link "Library/Application Support/Code/User/settings.json"

source "${HOME}/.profile"
