#!/usr/bin/env bash
# Persists the currently installed packages for brew, cask, mas, and vscode
set -eu

brew tap > brew-tap-requirements.txt
brew leaves > brew-requirements.txt
brew cask list > brew-cask-requirements.txt
pip3 freeze > python-requirements.txt
mas list > mas-requirements.txt
code --list-extensions > vscode-requirements.txt
