#!/usr/bin/env bash
# Quickly decodes each section of the JWT
set -eu

TOKEN=$(cat)

cut -d . -f 1 <(echo "${TOKEN}") | base64 -D | jq
cut -d . -f 2 <(echo "${TOKEN}") | base64 -D | jq
cut -d . -f 3 <(echo "${TOKEN}")
