#!/usr/bin/env bash
set -eu -o pipefail

main() {
    a="${1}"
    b="${2}"
    shift; shift
    cmd="$@"
    orig="$(kubectx -c)"

    kubectx "${a}"
    kubectl ${cmd}

    kubectx "${b}"
    kubectl ${cmd}

    kubectx "${orig}" 2>/dev/null 1>/dev/null
}

main "$@"
