#!/usr/bin/env bash
# Get kubeconfig from rancher, merge with ~/.kube/config and start using immediately
set -eu -o pipefail

main() {
  local temp_file="/tmp/rancher-kube-config"
  local cluster_name="${1}"

  mkdir -p "${HOME}/.kube"
  rancher clusters kf "${cluster_name}" > "${temp_file}"
  merge-kubectl "${temp_file}"
  rm "${temp_file}"

  kubectl config use-context "${cluster_name}"
}

main "$@"
